blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.post_list,name='post_list'),
    path('<int:id>',views.post_detail,name='post_detail'),
    path('tags=<slug:tag>', views.post_by_tag, name='post_by_tag'),
    path('category=<slug:category>', views.post_by_category, name='post_by_category'),

]

meals/urls.py

from django.urls import path
from . import views

app_name = 'meals'

urlpatterns = [
    path('', views.meal_list,name='meal_list'),
    path('<slug:slug>',views.meal_detail,name='meal_detail')
]

project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [

    path('summernote/', include('django_summernote.urls')),

    path('admin/', admin.site.urls),
    path('meals/',include('meals.urls',namespace='meals')),
    path('blog/',include('blog.urls',namespace='blog')),
    path('contact/',include('contact.urls',namespace='contact')),
    path('reserve_table/',include('reservation.urls',namespace='reservation')),
    path('about-us/',include('aboutus.urls',namespace='aboutus')),
    path('',include('home.urls',namespace='home')),
]



urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)



admin.site.site_header = "Resturant AdminPanel"
admin.site.site_header = "Resturant App Admin"
admin.site.index_title = "Welcome to Resturant Admin Panel"








meals/models.py
from django.db import models
from django.utils.text import slugify
# Create your models here.


class Meals(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField(max_length=500)
    category = models.ForeignKey('Category', on_delete=models.SET_NULL, null=True)
    people = models.IntegerField()
    price = models.DecimalField(max_digits=5,decimal_places=2)
    preperation_time = models.IntegerField()
    image = models.ImageField(upload_to='meals/')
    slug = models.SlugField(blank=True,null=True)


    def save(self,*args,**kwargs):
        if not self.slug and self.name :
            self.slug = slugify(self.name)
        super(Meals,self).save(*args,**kwargs)


    class Meta:
        verbose_name = 'meal'
        verbose_name_plural = 'meals'



    def __str__(self):
        return self.name

class Category(models.Model):
    name = models.CharField(max_length=30)


    class Meta:
        verbose_name = 'category'
        verbose_name_plural = 'categories'


    def __str__(self):
        return self.name


meals/views.py
from django.shortcuts import render

# Create your views here.
from .models import Meals,Category

def meal_list(request):
    meal_list = Meals.objects.all()
    categories = Category.objects.all()

    context = {
        'meal_list':meal_list ,
        'categories':categories,
    }

    return render(request,'Meals/list.html',context)



def meal_detail(request,slug):
    meal_detail = Meals.objects.get(slug=slug)

    context = {'meal_detail':meal_detail}

    return render(request, 'Meals/detail.html',context)

meals/templates/Meals/detail.html
{% extends 'base.html' %}
{% block body %}

      <div class="main-wrap">
        <div class="cover_1">
          <div class="img_bg" style="background-image: url(img/slider-1.jpg);" data-stellar-background-ratio="0.5">
            <div class="container">
              <div class="row align-items-center">
                <div class="col-md-12" data-aos="fade-up">
                  <h2 class="heading">Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit ipsa sint amet aliquam velit minima tenetur quisquam beatae molestiae possimus dicta.</h2>
                </div>
              </div>
            </div>
          </div>
        </div> <!-- .cover_1 -->




        {% comment %}
        <div class="section">
          <div class="container">
            <div class="row justify-content-center">
              <div class="col-md-7 text-center"  data-aos="fade-up">
                <h2 class="mb-4">Our Specialties</h2>
                <p class="lead">Lorem ipsum dolor sit amet consectetur adipisicing elit. Beatae eum voluptatem odio expedita laborum fugit repudiandae dolorem consectetur.</p>
              </div>
            </div>
          </div>
        </div> <!-- .section -->

        <div class="section pt-0 pb-0">

          <div class="menus d-flex bg-light">
            <div class="d-flex item">
              <div class="image" style="background-image: url(img/img_1.jpg);" data-aos="fade"></div>
              <div class="text">
                <h3>Grilled Egg With Garlic</h3>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur illo quisquam saepe quaerat.</p>
                <p class="price">$5.00</p>
              </div>
            </div> <!-- .item -->

            <div class="d-flex item">
              <div class="image order-2 order-md-1"  style="background-image: url(img/img_2.jpg);" data-aos="fade" data-aos-delay="100"></div>
              <div class="text order-1 order-md-2">
                <h3>Organic Tomato Salad</h3>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur illo quisquam saepe quaerat.</p>
                <p class="price">$6.00</p>
              </div>
            </div> <!-- .item -->

            <div class="d-flex item">
              <div class="image order-1 order-md-2 order-lg-2 order-xl-1" style="background-image: url(img/img_3.jpg);" data-aos="fade" data-aos-delay="200"></div>
              <div class="text order-2 order-md-1 order-lg-1 order-xl-2">
                <h3>Flatbread</h3>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur illo quisquam saepe quaerat.</p>
                <p class="price">$9.00</p>

              </div>
            </div> <!-- .item -->

            <div class="d-flex item">
              <div class="image order-2" style="background-image: url(img/img_4.jpg);" data-aos="fade" data-aos-delay="300"></div>
              <div class="text order-1 mb-3">
                <h3>Rack Of Lamb</h3>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur illo quisquam saepe quaerat.</p>
                <p class="price">$13.00</p>
              </div>
            </div> <!-- .item -->

            <div class="d-flex item">
              <div class="image order-1 order-lg-1 order-xl-2" style="background-image: url(img/img_5.jpg);" data-aos="fade" data-aos-delay="400"></div>
              <div class="text order-2 order-lg-2 order-xl-1">
                <h3>Eggplant Parmigiana</h3>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur illo quisquam saepe quaerat.</p>
                <p class="price">$9.00</p>
              </div>
            </div> <!-- .item -->

            <div class="d-flex item">
              <div class="image order-2 order-md-1 order-lg-1 order-xl-2" style="background-image: url(img/img_6.jpg);" data-aos="fade" data-aos-delay="500"></div>
              <div class="text order-1 order-md-2 order-lg-2 order-xl-1">
                <h3>Spicy Meatballs</h3>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur illo quisquam saepe quaerat.</p>
                <p class="price">$7.00</p>
              </div>
            </div> <!-- .item -->

          </div>
        </div>
          {% endcomment %}






        <div class="section">
          <div class="container">
            <div class="row justify-content-center">
              <div class="col-md-8" data-aos="fade-up">

                    <img class="meal_img" src="{{meal_detail.image.url}}" alt = "">
                    <h2>{{meal_detail}}</h2>
                    <p>{{meal_detail.description}}</p>

                    <p>For : {{meal_detail.people}} People</p>
                    <p>Preperation Time : {{meal_detail.preperation_time}} Minutes</p>
                    <p>Price : ₹{{meal_detail.price}}</p>

              </div>
            </div>
          </div>
        </div>







      </div> <!-- .main-wrap -->
      {% endblock body %}



meals/templates/Meals/list.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
      
      <div class="main-wrap">
        <div class="cover_1">
          <div class="img_bg" style="background-image: url({% static 'site_static/img/slider-1.jpg' %})" data-stellar-background-ratio="0.5">
            <div class="container">
              <div class="row align-items-center">
                <div class="col-md-12" data-aos="fade-up">
                  <h2 class="heading">Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit ipsa sint amet aliquam velit minima tenetur quisquam beatae molestiae possimus dicta.</h2>
                </div>
              </div>
            </div>
          </div>
        </div> <!-- .cover_1 -->




        {% comment %}
        <div class="section">
          <div class="container">
            <div class="row justify-content-center">
              <div class="col-md-7 text-center"  data-aos="fade-up">
                <h2 class="mb-4">Our Specialties</h2>
                <p class="lead">Lorem ipsum dolor sit amet consectetur adipisicing elit. Beatae eum voluptatem odio expedita laborum fugit repudiandae dolorem consectetur.</p>
              </div>
            </div>
          </div>
        </div> <!-- .section -->
        
        <div class="section pt-0 pb-0">

          <div class="menus d-flex bg-light">
            <div class="d-flex item">
              <div class="image" style="background-image: url(img/img_1.jpg);" data-aos="fade"></div>
              <div class="text">
                <h3>Grilled Egg With Garlic</h3>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur illo quisquam saepe quaerat.</p>
                <p class="price">$5.00</p>
              </div>
            </div> <!-- .item -->

            <div class="d-flex item">
              <div class="image order-2 order-md-1"  style="background-image: url(img/img_2.jpg);" data-aos="fade" data-aos-delay="100"></div>
              <div class="text order-1 order-md-2">
                <h3>Organic Tomato Salad</h3>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur illo quisquam saepe quaerat.</p>
                <p class="price">$6.00</p>
              </div>
            </div> <!-- .item -->

            <div class="d-flex item">
              <div class="image order-1 order-md-2 order-lg-2 order-xl-1" style="background-image: url(img/img_3.jpg);" data-aos="fade" data-aos-delay="200"></div>
              <div class="text order-2 order-md-1 order-lg-1 order-xl-2">
                <h3>Flatbread</h3>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur illo quisquam saepe quaerat.</p>
                <p class="price">$9.00</p>
                
              </div>
            </div> <!-- .item -->

            <div class="d-flex item">
              <div class="image order-2" style="background-image: url(img/img_4.jpg);" data-aos="fade" data-aos-delay="300"></div>
              <div class="text order-1 mb-3">
                <h3>Rack Of Lamb</h3>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur illo quisquam saepe quaerat.</p>
                <p class="price">$13.00</p>
              </div>
            </div> <!-- .item -->

            <div class="d-flex item">
              <div class="image order-1 order-lg-1 order-xl-2" style="background-image: url(img/img_5.jpg);" data-aos="fade" data-aos-delay="400"></div>
              <div class="text order-2 order-lg-2 order-xl-1">
                <h3>Eggplant Parmigiana</h3>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur illo quisquam saepe quaerat.</p>
                <p class="price">$9.00</p>
              </div>
            </div> <!-- .item -->

            <div class="d-flex item">
              <div class="image order-2 order-md-1 order-lg-1 order-xl-2" style="background-image: url(img/img_6.jpg);" data-aos="fade" data-aos-delay="500"></div>
              <div class="text order-1 order-md-2 order-lg-2 order-xl-1">
                <h3>Spicy Meatballs</h3>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur illo quisquam saepe quaerat.</p>
                <p class="price">$7.00</p>
              </div>
            </div> <!-- .item -->

          </div>
        </div>
          {% endcomment %}






        <div class="section">
          <div class="container">
            <div class="row justify-content-center">
              <div class="col-md-8" data-aos="fade-up">

                <h2 class="mb-5 text-center">Menu List with Price</h2>


                  <ul class="nav site-tab-nav" id="pills-tab" role="tablist">
                      {% for category in categories %}
                        <li class="nav-item">
                            <a class="nav-link" id="{{category}}-tab" data-toggle="pill" href="{{category}}" role="tab" aria-controls="{{category}}" aria-selected="true">Breakfast</a>
                        </li>
                      {% endfor %}
                      <div class="tab-content" id="pills-tabContent">
                          {% for category in categories %}
                              <div class="tab-pane fade show active" id="{{category}}" role="tabpanel" aria-labelledby="{{category}}-tab">


                                  {% for meal in meal_list %}
                                    {% if meal.category == category %}
                                          <div class="d-block d-md-flex menu-food-item">
                                          <div class="text order-1 mb-3">
                                            <h3><a href="{% url 'meals:meal_detail' meal.slug %}">{{meal.name}}</a></h3>
                                            <p>{{meal.description}}</p>
                                          </div>
                                          <div class="price order-2">
                                            <strong>₹{{meal.price}}</strong>
                                          </div>
                                        </div> <!-- .menu-food-item -->
                                    {% endif %}
                                  {% endfor %}
                              </div>
                    {% endfor %}



                  <div class="tab-pane fade" id="pills-lunch" role="tabpanel" aria-labelledby="pills-lunch-tab">

                    <div class="d-block d-md-flex menu-food-item">
                      <div class="text order-1 mb-3">
                        <h3><a href="#">Jumbo Lump Crab Stack</a></h3>
                        <p>Spinach and artichokes in a creamy cheese dip with warm tortilla chips &amp; salsa.</p>
                      </div>
                      <div class="price order-2">
                        <strong>$12.49</strong>
                      </div>
                    </div> <!-- .menu-food-item -->

                    <div class="d-block d-md-flex menu-food-item">
                      <div class="text order-1 mb-3">
                        <h3><a href="#">Jamaican Chicken Wings</a></h3>
                        <p>Crisp tortilla and plantain chips covered with lightly spiced ground beef, melted cheese, pickled jalapeños, guacamole, sour cream and salsa.</p>
                      </div>
                      <div class="price order-2">
                        <strong>$15.99</strong>
                      </div>
                    </div> <!-- .menu-food-item -->

                    <div class="d-block d-md-flex menu-food-item">
                      <div class="text order-1 mb-3">
                        <h3><a href="#">Bahamian Seafood Chowder</a></h3>
                        <p>A heaping mountain of rings, handmade with Panko breading and shredded coconut flakes.</p>
                      </div>
                      <div class="price order-2">
                        <strong>$10.99</strong>
                      </div>
                    </div> <!-- .menu-food-item -->

                    <div class="d-block d-md-flex menu-food-item">
                      <div class="text order-1 mb-3">
                        <h3><a href="#">Grilled Chicken &amp; Tropical Fruit on Mixed Greens</a></h3>
                        <p>Lobster and tender shrimp, with onions, sweet peppers, spinach and our three cheese blend. Griddled and served with tomato salsa and sour cream.</p>
                      </div>
                      <div class="price order-2">
                        <strong>$12.99</strong>
                      </div>
                    </div> <!-- .menu-food-item -->

                  </div>
                  <div class="tab-pane fade" id="pills-dinner" role="tabpanel" aria-labelledby="pills-dinner-tab">
                    
                    <div class="d-block d-md-flex menu-food-item">
                      <div class="text order-1 mb-3">
                        <h3><a href="#">Grilled Top Sirlion Steak</a></h3>
                        <p>Spinach and artichokes in a creamy cheese dip with warm tortilla chips &amp; salsa.</p>
                      </div>
                      <div class="price order-2">
                        <strong>₹18.99</strong>
                      </div>
                    </div> <!-- .menu-food-item -->

                    <div class="d-block d-md-flex menu-food-item">
                      <div class="text order-1 mb-3">
                        <h3><a href="#">Steak Oscar</a></h3>
                        <p>Crisp tortilla and plantain chips covered with lightly spiced ground beef, melted cheese, pickled jalapeños, guacamole, sour cream and salsa.</p>
                      </div>
                      <div class="price order-2">
                        <strong>₹23.99</strong>
                      </div>
                    </div> <!-- .menu-food-item -->

                    <div class="d-block d-md-flex menu-food-item">
                      <div class="text order-1 mb-3">
                        <h3><a href="#">Skirt Steak Churrasco</a></h3>
                        <p>A heaping mountain of rings, handmade with Panko breading and shredded coconut flakes.</p>
                      </div>
                      <div class="price order-2">
                        <strong>₹20.99</strong>
                      </div>
                    </div> <!-- .menu-food-item -->

                    <div class="d-block d-md-flex menu-food-item">
                      <div class="text order-1 mb-3">
                        <h3><a href="#">Grilled Beef Steak</a></h3>
                        <p>Lobster and tender shrimp, with onions, sweet peppers, spinach and our three cheese blend. Griddled and served with tomato salsa and sour cream.</p>
                      </div>
                      <div class="price order-2">
                        <strong>₹20.99</strong>
                      </div>
                    </div> <!-- .menu-food-item -->

                  </div>
                </div>


              </div>
            </div>
          </div>
        </div>





        

      </div> <!-- .main-wrap -->
      {% endblock body %}