blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.post_list,name='post_list'),
    path('<int:id>',views.post_detail,name='post_detail'),
    path('tags=<slug:tag>', views.post_by_tag, name='post_by_tag'),
    path('category=<slug:category>', views.post_by_category, name='post_by_category'),

]

contact/urls.py
from django.urls import path
from . import views

app_name = 'contact'

urlpatterns = [
    path('', views.send_email,name='send_email'),
    path('success/', views.send_success,name='send_success'),

]

meals/urls.py

from django.urls import path
from . import views

app_name = 'meals'

urlpatterns = [
    path('', views.meal_list,name='meal_list'),
    path('<slug:slug>',views.meal_detail,name='meal_detail')
]

project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [

    path('summernote/', include('django_summernote.urls')),

    path('admin/', admin.site.urls),
    path('meals/',include('meals.urls',namespace='meals')),
    path('blog/',include('blog.urls',namespace='blog')),
    path('contact/',include('contact.urls',namespace='contact')),
    path('reserve_table/',include('reservation.urls',namespace='reservation')),
    path('about-us/',include('aboutus.urls',namespace='aboutus')),
    path('',include('home.urls',namespace='home')),
]



urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)



admin.site.site_header = "Resturant AdminPanel"
admin.site.site_header = "Resturant App Admin"
admin.site.index_title = "Welcome to Resturant Admin Panel"








reservation/urls.py



from django.urls import path
from . import views

app_name = 'reservation'

urlpatterns = [
    path('', views.reserve_table,name='reserve_table'),
]

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <title>Colorlib Diner</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://fonts.googleapis.com/css?family=Playfair+Display:300,400,700,800|Open+Sans:300,400,700" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'site_static/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'site_static/css/animate.css' %}">
    <link rel="stylesheet" href="{% static 'site_static/css/owl.carousel.min.css' %}">

    <link rel="stylesheet" href="{% static 'site_static/css/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static 'site_static/css/aos.css' %}">

    <link rel="stylesheet" href="{% static 'site_static/css/bootstrap-datepicker.css' %}">
    <link rel="stylesheet" href="{% static 'site_static/css/jquery.timepicker.css' %}">

    <link rel="stylesheet" href="{% static 'site_static/fonts/ionicons/css/ionicons.min.css' %}">
    <link rel="stylesheet" href="{% static 'site_static/fonts/fontawesome/css/font-awesome.min.css' %}">

    <link rel="stylesheet" href="{% static 'site_static/fonts/flaticon/font/flaticon.css' %}">


    <link rel="stylesheet" href="{% static 'site_static/css/style.css' %}">
  </head>
  <body>
    

    <div class="site-wrap">
      
      <nav class="site-menu">
        <div class="site-menu-inner">
          <ul class="list-unstyled">
            <li class="active"><a href="/">Home</a></li>
            <li><a href="{% url 'meals:meal_list' %}">Meals</a></li>
            <li><a href="{% url 'blog:post_list' %}">Our Blog</a></li>
            <li><a href="{% url 'reservation:reserve_table' %}">Reserve A Table</a></li>
            <li><a href="{% url 'contact:send_email' %}">Contact</a></li>
          </ul>
        </div>
      </nav>

      <header class="site-header">
        <div class="row align-items-center">
          <div class="col-5 col-md-3">
             <ul class="list-unstyled social">
              <li><a href="#"><span class="fa fa-facebook"></span></a></li>
              <li><a href="#"><span class="fa fa-twitter"></span></a></li>
              <li><a href="#"><span class="fa fa-instagram"></span></a></li>
            </ul>
          </div>
          <div class="col-2 col-md-6 text-center">
            <a href="index.html" class="site-logo">D</a>
          </div>
          <div class="col-5 col-md-3 text-right menu-burger-wrap">
            <a href="#" class="site-nav-toggle js-site-nav-toggle"><i></i></a>

          </div>
        </div>
       
      </header> <!-- site-header -->
      
      {% block body %}
      {% endblock body %}
      

      <footer>
        <div class="site-footer">
          <div class="container">
            <div class="row small-gutters mb-5">
              <div class="col-md-6 col-lg-3 mb-5" data-aos="fade" data-aos-delay="100">
                <div class="footer-widget">
                  <h3>Diner Restaurant</h3>
                  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel neque, odio illum. Est minima sint minus sunt ducimus.</p>
                </div>
              </div>
              <div class="col-md-6 col-lg-3 mb-5" data-aos="fade" data-aos-delay="200">
                <div class="footer-widget">
                  <h3>Lunch Service</h3>
                  <p>Booking from 12:00pm - 1:30pm</p>
                  <h3>Dinner Service</h3>
                  <p>Everyday: <br> Booking from 6:00pm - 9:00pm</p>
                </div>
              </div>
              <div class="col-md-6 col-lg-3 mb-5" data-aos="fade" data-aos-delay="300">
                <div class="footer-widget">
                  <h3>Quick Links</h3>
                  <ul>
                    <li><a href="#">Help &amp; Support</a></li>
                    <li><a href="#">Privacy Policy</a></li>
                    <li><a href="#">Get in Touch</a></li>
                    <li><a href="#">Testimonials</a></li>
                  </ul>
                </div>
              </div>
              <div class="col-md-6 col-lg-3 mb-5" data-aos="fade" data-aos-delay="400">
                <div class="footer-widget footer-contact-widget">

                  <h3>Subscribe</h3>
                  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
                  <form action="" class="form-subscribe mb-5">
                    <div class="form-group form-field">
                      <input type="submit" value="Send" class="btn btn-primary">
                      <input type="text" class="form-control" placeholder="Email">
                    </div>
                  </form>

                  <h3>Contact Us</h3>
                  <p class="contact-email">info@yourdomain.com</p>
                  <p class="contact-phone">1-444-123-9829</p>
                  
                  
                </div>
              </div>
            </div>
          </div>
          
        </div>
      </footer>

      <div class="site-footer-copyright">
        <div class="container">
          <div class="row">

             <p class="footer-text col-md-12"><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>
          </div>
        </div>
      </div>

    </div>

    <!-- loader -->
    <div id="loader" class="show fullscreen"><svg class="circular" width="48px" height="48px"><circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/><circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#f4b214"/></svg></div>

    <script src="{% static 'site_static/js/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static 'site_static/js/jquery-migrate-3.0.1.min.js' %}"></script>
    <script src="{% static 'site_static/js/popper.min.js' %}"></script>
    <script src="{% static 'site_static/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'site_static/js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'site_static/js/jquery.waypoints.min.js' %}"></script>

    <script src="{% static 'site_static/js/bootstrap-datepicker.js' %}"></script>
    <script src="{% static 'site_static/js/jquery.timepicker.min.js' %}"></script>
    <script src="{% static 'site_static/js/jquery.stellar.min.js' %}"></script>

    <script src="{% static 'site_static/js/aos.js' %}"></script>
    

    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false"></script>

    <script src="{% static 'site_static/js/main.js' %}"></script>
  </body>
</html>